### ISSUE TITLE
Some obstacles to use

### ISSUE THREAD

**Issue by childeyouyu** [Thisal-D/tkchart#2]
The cget() function was not found, how should I go about getting the relevant parameter values? Also, the x-axis coordinate display function doesn't seem to be available?

---

没有发现cget()函数，我应该怎样去获取相关的参数值？此外，x轴坐标显示功能似乎也没有？

**Comment by childeyouyu** [comment]
My main requirement is to set a specified number of points for the x-axis and set (5-10) x-coordinate values as needed, but I can't find where to set the coordinate values at the moment, and based on the docs I've come to the conclusion that the number of x's needs to rely on the realization of the chart_line_len=width/n, and I'm not able to find any way related to obtaining the width (the width changes, and you can't use the initial value)

---

我的主要需求是，为X轴设置指定数量的点，并根据需要设置（5-10）个x坐标值，但目前没找到设置坐标值的位置，根据文档得出的结论是x的数量需要依靠chart_line_len=width/n实现，我又没能找到与获取width相关的方法（width变化，不能使用初始值）

**Comment by Thisal-D** [comment]
this is a simple project, right now there is no way to set values to x axis..! but i'm working on updating this package totally..i'll update this package soon..

**Comment by Thisal-D** [comment]
> My main requirement is to set a specified number of points for the x-axis and set (5-10) x-coordinate values as needed, but I can't find where to set the coordinate values at the moment, and based on the docs I've come to the conclusion that the number of x's needs to rely on the realization of the chart_line_len=width/n, and I'm not able to find any way related to obtaining the width (the width changes, and you can't use the initial value)
> 
> 我的主要需求是，为X轴设置指定数量的点，并根据需要设置（5-10）个x坐标值，但目前没找到设置坐标值的位置，根据文档得出的结论是x的数量需要依靠chart_line_len=width/n实现，我又没能找到与获取width相关的方法（width变化，不能使用初始值）
![Screenshot 2024-01-10 082559](https://github.com/Thisal-D/tkchart/assets/93121062/2f5864b1-9848-49e9-a97c-1ebcb06bf7cb)
i'm working on it :D

**Comment by childeyouyu** [comment]
> > My main requirement is to set a specified number of points for the x-axis and set (5-10) x-coordinate values as needed, but I can't find where to set the coordinate values at the moment, and based on the docs I've come to the conclusion that the number of x's needs to rely on the realization of the chart_line_len=width/n, and I'm not able to find any way related to obtaining the width (the width changes, and you can't use the initial value)我的主要要求是为 x 轴设置指定数量的点并根据需要设置 （5-10） x 坐标值，但我目前找不到在哪里设置坐标值，根据文档我得出的结论是 x 的数量需要依赖于 chart_line_len=width/n 的实现， 并且我找不到任何与获取宽度相关的方法（宽度发生变化，您不能使用初始值）
> > 我的主要需求是，为X轴设置指定数量的点，并根据需要设置（5-10）个x坐标值，但目前没找到设置坐标值的位置，根据文档得出的结论是x的数量需要依靠chart_line_len=width/n实现，我又没能找到与获取width相关的方法（width变化，不能使用初始值）
> > ![Screenshot 2024-01-10 082559](https://private-user-images.githubusercontent.com/93121062/295423554-2f5864b1-9848-49e9-a97c-1ebcb06bf7cb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4OTc4NzgsIm5iZiI6MTcwNDg5NzU3OCwicGF0aCI6Ii85MzEyMTA2Mi8yOTU0MjM1NTQtMmY1ODY0YjEtOTg0OC00OWU5LWE5N2MtMWViY2IwNmJmN2NiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEwVDE0MzkzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdjNGUxNmE2MTU4YjA0YjI0MTZmYTNhNmY4MDc0MDlmYWYyYzA1NDg5OTUwMGY5ZmRkNDAwYzdjNzRmODk0YmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kHQPZgtBVeulDSHK2oHDtawLZsi2sDVFnutMjVWp16c)
> > i'm working on it :D

cool!

**Comment by Thisal-D** [comment]
i updated the package . please check README.md before use this.

**Comment by childeyouyu** [comment]
> i updated the package . please check README.md before use this.我更新了软件包。请在使用前检查 README.md。

I will try after go home.

**Comment by Thisal-D** [comment]
> > i updated the package . please check README.md before use this.我更新了软件包。请在使用前检查 README.md。
> 
> I will try after go home.

💯

**Comment by childeyouyu** [comment]
a pronlem:
![image](https://github.com/Thisal-D/tkchart/assets/89082776/5e9bc900-1ab6-43c5-abe8-1a04b37ddfa6)

The other problem is that if I enter x_data_max=60, maybe I want to display up to 60 points on the screen instead of having to adjust it again via line_width.
A better logic I can think of is to design a list for the x-axis, and determine the scale of the x-axis by the length of the list (the list can be int, str), in this case, by the value of the list (x_min, x_max).

**Comment by Thisal-D** [comment]
> a problem:
> ![image](https://github.com/Thisal-D/tkchart/assets/89082776/5e9bc900-1ab6-43c5-abe8-1a04b37ddfa6)
> 
> The other problem is that if I enter x_data_max=60, maybe I want to display up to 60 points on the screen instead of having to adjust it again via line_width.
> A better logic I can think of is to design a list for the x-axis, and determine the scale of the x-axis by the length of the list (the list can be int, str), in this case, by the value of the list (x_min, x_max).

You mean when you set x_data as  [1,2,3,4,5,6,7,8,9,10]  you wanna set these values to x-axis and set line_width automatically  by depend on len of this list?By the way i really appreciate you dude for your support.

**Comment by Thisal-D** [comment]
> a problem:
> ![image](https://github.com/Thisal-D/tkchart/assets/89082776/5e9bc900-1ab6-43c5-abe8-1a04b37ddfa6)
> 
> The other problem is that if I enter x_data_max=60, maybe I want to display up to 60 points on the screen instead of having to adjust it again via line_width.
> A better logic I can think of is to design a list for the x-axis, and determine the scale of the x-axis by the length of the list (the list can be int, str), in this case, by the value of the list (x_min, x_max).

I will fix this error just don't configure line_width. just pass it when creating the LineChart.

**Comment by childeyouyu** [comment]
@Thisal-D 
Yes, it seems to me that the number of points shown is determined by [1,2,3,4]. A step further would be to allow x to change over time like y. For example, if I set x: [4,5,6,7], then I could update x from 4-7 instead of 1-7.
By the way, if I want to freely make changes to the display state of the curve, how do I do that? For example hiding and redisplaying the curve.

---

It's the ones who do open source that are great, I'm just offering some of my own insights and needs haha。
Looking forward to your next update!

**Comment by Thisal-D** [comment]
i fixed

> > a problem:
> > ![image](https://private-user-images.githubusercontent.com/89082776/296634640-5e9bc900-1ab6-43c5-abe8-1a04b37ddfa6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzNDIzMzksIm5iZiI6MTcwNTM0MjAzOSwicGF0aCI6Ii84OTA4Mjc3Ni8yOTY2MzQ2NDAtNWU5YmM5MDAtMWFiNi00M2M1LWFiZTgtMWEwNGIzN2RkZmE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE1VDE4MDcxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkwZDA2ZTA3YmYyM2RhOTNlYzg0OGE4YmFmN2Y5NGRiNTQ1OTg3OThlNjJkZjY1NDkzYWU4ZWNiMmFiMWYwOWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.F-6e9i7XWApl51zPAb7LJiy0I0NIx7rNbgf75-Vut1Y)
> > The other problem is that if I enter x_data_max=60, maybe I want to display up to 60 points on the screen instead of having to adjust it again via line_width.
> > A better logic I can think of is to design a list for the x-axis, and determine the scale of the x-axis by the length of the list (the list can be int, str), in this case, by the value of the list (x_min, x_max).
> 
> I will fix this error just don't configure line_width. just pass it when creating the LineChart.



> a problem: ![image](https://private-user-images.githubusercontent.com/89082776/296634640-5e9bc900-1ab6-43c5-abe8-1a04b37ddfa6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzNDIzMzksIm5iZiI6MTcwNTM0MjAzOSwicGF0aCI6Ii84OTA4Mjc3Ni8yOTY2MzQ2NDAtNWU5YmM5MDAtMWFiNi00M2M1LWFiZTgtMWEwNGIzN2RkZmE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE1VDE4MDcxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkwZDA2ZTA3YmYyM2RhOTNlYzg0OGE4YmFmN2Y5NGRiNTQ1OTg3OThlNjJkZjY1NDkzYWU4ZWNiMmFiMWYwOWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.F-6e9i7XWApl51zPAb7LJiy0I0NIx7rNbgf75-Vut1Y)
> 
> The other problem is that if I enter x_data_max=60, maybe I want to display up to 60 points on the screen instead of having to adjust it again via line_width. A better logic I can think of is to design a list for the x-axis, and determine the scale of the x-axis by the length of the list (the list can be int, str), in this case, by the value of the list (x_min, x_max).

I fixed this bug and updated for your requirement..

**Comment by Thisal-D** [comment]
> i fixed
> 
> > > a problem:
> > > ![image](https://private-user-images.githubusercontent.com/89082776/296634640-5e9bc900-1ab6-43c5-abe8-1a04b37ddfa6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzNDIzMzksIm5iZiI6MTcwNTM0MjAzOSwicGF0aCI6Ii84OTA4Mjc3Ni8yOTY2MzQ2NDAtNWU5YmM5MDAtMWFiNi00M2M1LWFiZTgtMWEwNGIzN2RkZmE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE1VDE4MDcxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkwZDA2ZTA3YmYyM2RhOTNlYzg0OGE4YmFmN2Y5NGRiNTQ1OTg3OThlNjJkZjY1NDkzYWU4ZWNiMmFiMWYwOWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.F-6e9i7XWApl51zPAb7LJiy0I0NIx7rNbgf75-Vut1Y)
> > > The other problem is that if I enter x_data_max=60, maybe I want to display up to 60 points on the screen instead of having to adjust it again via line_width.
> > > A better logic I can think of is to design a list for the x-axis, and determine the scale of the x-axis by the length of the list (the list can be int, str), in this case, by the value of the list (x_min, x_max).
> > 
> > 
> > I will fix this error just don't configure line_width. just pass it when creating the LineChart.
> 
> > a problem: ![image](https://private-user-images.githubusercontent.com/89082776/296634640-5e9bc900-1ab6-43c5-abe8-1a04b37ddfa6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzNDIzMzksIm5iZiI6MTcwNTM0MjAzOSwicGF0aCI6Ii84OTA4Mjc3Ni8yOTY2MzQ2NDAtNWU5YmM5MDAtMWFiNi00M2M1LWFiZTgtMWEwNGIzN2RkZmE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE1VDE4MDcxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkwZDA2ZTA3YmYyM2RhOTNlYzg0OGE4YmFmN2Y5NGRiNTQ1OTg3OThlNjJkZjY1NDkzYWU4ZWNiMmFiMWYwOWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.F-6e9i7XWApl51zPAb7LJiy0I0NIx7rNbgf75-Vut1Y)
> > The other problem is that if I enter x_data_max=60, maybe I want to display up to 60 points on the screen instead of having to adjust it again via line_width. A better logic I can think of is to design a list for the x-axis, and determine the scale of the x-axis by the length of the list (the list can be int, str), in this case, by the value of the list (x_min, x_max).
> 
> I fixed this bug and updated for your requirement..

# Check readme before use, little changes :D
## check test/tests4.py   example

**Comment by Thisal-D** [comment]
## By the way, if I want to freely make changes to the display state of the curve, how do I do that? For example hiding and redisplaying the curve.  

i didnt undestand ? can u explain this more ?

**Comment by childeyouyu** [comment]
> ## By the way, if I want to freely make changes to the display state of the curve, how do I do that? For example hiding and redisplaying the curve.
> 顺便说一下，如果我想自由地更改曲线的显示状态，我该怎么做？例如，隐藏和重新显示曲线。
> i didnt undestand ? can u explain this more ?我没有 undestand ？你能解释一下吗？

It's when I add a curve to a graph, but instead of displaying it, I control him with a parameter.
When the curve state is on, the curve appears on the graph, otherwise the curve is just generated but not displayed. When doing data presentation, it is often the case that you need to show different images, or even hide them and then show them again.

**Comment by Thisal-D** [comment]
its possible...!
i'll make method for that :D

**Comment by Thisal-D** [comment]
ifu wanna hide whole chart , u can use place_foget ... if not the whole chart i'll cerate method for  that

**Comment by childeyouyu** [comment]
只要尝试一下，目前我正每次更新就刷新整个表格。

**Comment by Thisal-D** [comment]
https://github.com/Thisal-D/tkchart/assets/93121062/4b5d9210-7727-45b8-9a33-967fd0f6c828

is this what u need ?


> Give it a try, I'm now refreshing the entire form with every update.

**Comment by childeyouyu** [comment]
> 2024-01-16.09-15-07.X264123.mov 
> is this what u need ?
> 
> > Give it a try, I'm now refreshing the entire form with every update.试一试，我现在每次更新都会刷新整个表单。

Yes，it`s perfect!

**Comment by Thisal-D** [comment]
> > 2024-01-16.09-15-07.X264123.mov 
> > is this what u need ?
> > 
> > > Give it a try, I'm now refreshing the entire form with every update.试一试，我现在每次更新都会刷新整个表单。
> 
> Yes，it`s perfect!

Ok.give me 10mins i'll update 🙂

**Comment by Thisal-D** [comment]
> > 2024-01-16.09-15-07.X264123.mov 
> > is this what u need ?
> > 
> > > Give it a try, I'm now refreshing the entire form with every update.试一试，我现在每次更新都会刷新整个表单。
> 
> Yes，it`s perfect!
You have any other requirements ?

**Comment by Thisal-D** [comment]
> > 2024-01-16.09-15-07.X264123.mov 
> > is this what u need ?
> > 
> > > Give it a try, I'm now refreshing the entire form with every update.试一试，我现在每次更新都会刷新整个表单。
> 
> Yes，it`s perfect!

Do you have any other requirements ?

**Comment by childeyouyu** [comment]
So far, everything is OK.

**Comment by Thisal-D** [comment]
i updated package in pypi and github... nothing changed this time. but added new methods . 
 ### check "test/test5.py" to hide  and place_forget methods...

**Comment by childeyouyu** [comment]
Okay, I'm going to use it.

**Comment by Thisal-D** [comment]
Let me know if there is any bug or something I aint 100% sure about.

**Comment by childeyouyu** [comment]
uh ，hide函数需要一些修改，增加一个line参数让我去选择隐藏某一个line，而不是始终隐藏全部？

**Comment by childeyouyu** [comment]
Besides, test5 is not uploaded

**Comment by Thisal-D** [comment]
> Uh , the hide function needs some modification to add a line parameter that lets me go ahead and choose to hide a particular line instead of always hiding all of them?   

Then i need more time ..but maybe it will be possible.

**Comment by Thisal-D** [comment]
> Besides, test5 is not uploaded

🫤

**Comment by Thisal-D** [comment]
> Uh , the hide function needs some modification to add a line parameter that lets me go ahead and choose to hide a particular line instead of always hiding all of them?   

I have a idea.I'm working on it..

**Comment by Thisal-D** [comment]
updated the package ...! 
check out  ## test/test5.py &  test/test6.py

**Comment by Thisal-D** [comment]
> Uh , the hide function needs some modification to add a line parameter that lets me go ahead and choose to hide a particular line instead of always hiding all of them?

.........

**Comment by childeyouyu** [comment]
> > Uh , the hide function needs some modification to add a line parameter that lets me go ahead and choose to hide a particular line instead of always hiding all of them?
> 
> .........

I went to do some other work today, didn't have time to look at the new code, and may be involved in testing later.
If there are currently five lines, can they be hidden with five buttons?

**Comment by Thisal-D** [comment]
[2024-01-17 14-50-23.webm](https://github.com/Thisal-D/tkchart/assets/93121062/accaf2b1-a8ae-42c7-a54c-4be523827471)

###    i think this is what you ask for


> > > Uh , the hide function needs some modification to add a line parameter that lets me go ahead and choose to hide a particular line instead of always hiding all of them?
> > 
> > 
> > .........
> 
> I went to do some other work today, didn't have time to look at the new code, and may be involved in testing later. If there are currently five lines, can they be hidden with five buttons?



> > > Uh , the hide function needs some modification to add a line parameter that lets me go ahead and choose to hide a particular line instead of always hiding all of them?
> > 
> > 
> > .........
> 
> I went to do some other work today, didn't have time to look at the new code, and may be involved in testing later. If there are currently five lines, can they be hidden with five buttons?

**Comment by childeyouyu** [comment]
Exactly so from the video, that's what I'm hoping for, I'll integrate them into my program tomorrow, thank you so much for your support!

**Comment by childeyouyu** [comment]
Finished my job as my expected.
Thanke for your help, now I will to adjust some color for more beautiful.
![image](https://github.com/Thisal-D/tkchart/assets/89082776/60aac856-6924-44da-87a1-ee3ac13b84e5)

**Comment by Thisal-D** [comment]
> Finished my job as my expected.
> Thanke for your help, now I will to adjust some color for more beautiful.
> ![image](https://github.com/Thisal-D/tkchart/assets/89082776/60aac856-6924-44da-87a1-ee3ac13b84e5)
> 

Great job.💯🙂 Thanks for your ideas for tkchart pacakge.

By the way, Are you going to upload the project to github after you complete it? I really want to see your project🙂.

**Comment by childeyouyu** [comment]
Maybe, but it is made for a specially devices, other people hard to use it whitout the device.
Anyhow, I will show the completed for you.

Besides，I will do a new code for myself after a while, I will use tkchart again and it will be upload.

**Comment by Thisal-D** [comment]
> Maybe, but it is made for a specially devices, other people hard to use it whitout the device.
> Anyhow, I will show the completed for you.
> 
> Besides，I will do a new code for myself after a while, I will use tkchart again and it will be upload.

Ohh for special devices ,great work. I never thought my package would be used for such a thing, it's a simple package.

I wish your project will be successful.💯

**Comment by childeyouyu** [comment]
Wow, so big changed! 
The readme documentation is much prettier than before.
A lot of the parameters have changed, can you show a diagram of the previous one, identifying in each position what the corresponding parameter is?
The readme is missing an r in the anchor below the pack parameter.

**Comment by childeyouyu** [comment]
Can I contact you via social media? Too slow in github.
I found some bug in v1.2.0

**Comment by Thisal-D** [comment]
I have WhatsApp is that ok?

**Comment by Thisal-D** [comment]
> Can I contact you via social media? Too slow in github.
> I found some bug in v1.2.0

Sure check ur mail I send my FB ,

I fixed the missing 'r'.

**Comment by Thisal-D** [comment]
> Wow, so big changed! 
> The readme documentation is much prettier than before.
> A lot of the parameters have changed, can you show a diagram of the previous one, identifying in each position what the corresponding parameter is?
> The readme is missing an r in the anchor below the pack parameter.

I'll do that ? What's version are u using?

**Comment by Thisal-D** [comment]
> Wow, so big changed! The readme documentation is much prettier than before. A lot of the parameters have changed, can you show a diagram of the previous one, identifying in each position what the corresponding parameter is? The readme is missing an r in the anchor below the pack parameter.

i think this will help

# Changed
- bar_size -> axis_size
- bar_color -> axis_color
- chart_color -> fg_color
- sections_color -> section_color
- y_values_decimals -> y_axis_precision
- y_labels_count -> y_axis_label_count
- y_data -> y_axis_data
- y_data_max -> y_axis_max_value
- y_sections_count -> y_axis_section_count
- y_values_color -> y_axis_font_color
- y_data_color -> y_axis_data_font_color
- x_data -> x_axis_data
- x_sections_count -> x_axis_section_count
- x_values_color -> x_axis_font_color
- x_data_color -> x_axis_data_font_color
- x_y_data_font -> data_font_style
- x_y_values_font ->  axis_font_style


# Unchanged
- master
- width
- height 
- bg_color 
- line_width

# Removed
- x_data_min_max 
- x_labels_count 
- x_values_decimals 
- line_width_auto


# Newly added
- x_axis_values
- x_axis_data_position
- y_axis_data_position
- y_space
- x_space

**Comment by Thisal-D** [comment]
> Can I contact you via social media? Too slow in github. I found some bug in v1.2.0

What's the bug i wanna fix it :/

**Comment by childeyouyu** [comment]
Spring break is here and I'm on the train home.
It's not expected to get home until noon tomorrow.

---

The last bug I encountered yesterday was that in the configure method, the ability to configure y_axis_max_value (I think that's it, anyway it's the parameter that controls the maximum value of the Y-axis) doesn't take effect, i.e., after initializing it, it doesn't respond to me modifying it with configure again.

Also, I didn't find anything about the parameter that controls the number of points displayed on the graph, so maybe I missed it.

> ## I found some bug in v1.2.0
> What's Wrong, I want to fix it :/ Let me know as soon as possible

**Comment by Thisal-D** [comment]
> It's not expected to get home until noon tomorrow.

Thanks for bug report i'll fix it

**Comment by Thisal-D** [comment]
Now you can use the x_axis_values ​​parameter to set the X axis values. You can pass it as List or Tuple,
["a" ,"b","c" ,"d","e"]
[1, 2, 3, 4, 5, 6,7,8,9,10]
[0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8]

 The number of points displayed depends on the length of the list:

> Also, I didn't find anything about the parameter that controls the number of points displayed on the graph, so maybe I missed it.

**Comment by Thisal-D** [comment]
> The last bug I encountered yesterday was that in the configure method, the ability to configure y_axis_max_value (I think that's it, anyway it's the parameter that controls the maximum value of the Y-axis) doesn't take effect, i.e., after initializing it, it doesn't respond to me modifying it with configure again.



https://github.com/Thisal-D/tkchart/assets/93121062/bbe8afe9-930e-4969-86d1-fbf44bb5ef19


## its working , i dont  see any  problems

**Comment by childeyouyu** [comment]
> The number of points displayed depends on the length of the list.


This is an interesting way to give me some ideas, and I will make an attempt to set up a long list (maybe 1000 rows), most of which are [None], and place some value at the position of the quintile, either the time or the serial number (because displaying the x-coordinates of all the points is neither aesthetically pleasing nor necessary)

**Comment by Thisal-D** [comment]
sure i'll  add some way to control x axis label count. then u can use long list . nice idea its really worth doing,

> > The number of points displayed depends on the length of the list.
> 
> This is an interesting way to give me some ideas, and I will make an attempt to set up a long list (maybe 1000 rows), most of which are [None], and place some value at the position of the quintile, either the time or the serial number (because displaying the x-coordinates of all the points is neither aesthetically pleasing nor necessary)

**Comment by childeyouyu** [comment]
Perhaps there are some issues with my program code, but when I go back, I will try to reproduce it and see where the problem lies

> > The last bug I encountered yesterday was that in the configure method, the ability to configure y_axis_max_value (I think that's it, anyway it's the parameter that controls the maximum value of the Y-axis) doesn't take effect, i.e., after initializing it, it doesn't respond to me modifying it with configure again.
> 
>  2024-02-04.07-00-57.mp4 
> ## its working , i dont see any problems

**Comment by Thisal-D** [comment]
> Perhaps there are some issues with my program code, but when I go back, I will try to reproduce it and see where the problem lies
> 
> > > The last bug I encountered yesterday was that in the configure method, the ability to configure y_axis_max_value (I think that's it, anyway it's the parameter that controls the maximum value of the Y-axis) doesn't take effect, i.e., after initializing it, it doesn't respond to me modifying it with configure again.
> > 
> >  2024-02-04.07-00-57.mp4 
> > ## its working , i dont see any problems
> 
> 

Ok.
