### ISSUE TITLE
Reset chart : Feature

### ISSUE THREAD

**Issue by MohamSayed** [Thisal-D/tkchart#4]
**Is your feature request related to a problem? Please describe.**
Just simple feature to reset the chart.

**Describe the solution you'd like**
Added this function to LineChart class to reset the chart

```python
def reset(self):
    self.__reset_chart_info()
```

**Comment by Thisal-D** [comment]
> **Is your feature request related to a problem? Please describe.**
> Just simple feature to reset the chart.
> 
> **Describe the solution you'd like**
> Added this function to LineChart class to reset the chart
> 
> ```python
> def reset(self):
>     self.__reset_chart_info()
> ```
> 

Sure i'll do that , thank for the  idea
